# Generated by Django 2.1.2 on 2018-10-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('page_url', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.Company')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='schedules',
            field=models.ManyToManyField(to='cms.Schedule'),
        ),
    ]
