# Generated by Django 2.1.2 on 2018-10-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
