# Generated by Django 2.1.2 on 2018-10-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_content_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='group_name',
            new_name='page_section',
        ),
    ]
