# Generated by Django 2.1.2 on 2018-10-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20181016_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='cms.Schedule'),
        ),
        migrations.AddField(
            model_name='piece',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Content'),
        ),
    ]
