# Generated by Django 2.1.2 on 2018-10-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
